"""Initial migration

Revision ID: 59c4729a19c1
Revises: 
Create Date: 2025-12-18 17:38:11.728841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c4729a19c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_artist', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('nonce', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_wallet_address'), ['wallet_address'], unique=True)

    op.create_table('nfts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('token_standard', sa.Enum('ERC721', 'ERC1155', name='tokenstandard'), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_uri', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('royalty_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mint_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('is_listed', sa.Boolean(), nullable=True),
    sa.Column('is_burned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfts_contract_address'), ['contract_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfts_mint_tx_hash'), ['mint_tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfts_token_id'), ['token_id'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('price_eth', sa.String(length=78), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'CANCELLED', name='listingstatus'), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('list_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('sale_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('cancel_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('platform_fee_eth', sa.String(length=78), nullable=True),
    sa.Column('royalty_fee_eth', sa.String(length=78), nullable=True),
    sa.Column('seller_proceeds_eth', sa.String(length=78), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_listing_id'), ['listing_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('mint_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artwork_url', sa.String(length=500), nullable=False),
    sa.Column('token_standard', sa.Enum('ERC721', 'ERC1155', name='tokenstandardrequest'), nullable=True),
    sa.Column('edition_size', sa.Integer(), nullable=True),
    sa.Column('royalty_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('metadata_name', sa.String(length=200), nullable=True),
    sa.Column('metadata_description', sa.Text(), nullable=True),
    sa.Column('metadata_attributes', sa.Text(), nullable=True),
    sa.Column('image_ipfs_uri', sa.String(length=500), nullable=True),
    sa.Column('metadata_ipfs_uri', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MINTED', name='mintrequeststatus'), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('nft_id', sa.Integer(), nullable=True),
    sa.Column('mint_tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('minted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mint_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mint_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mint_requests_status'), ['status'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('tx_type', sa.Enum('MINT', 'TRANSFER', 'LIST', 'BUY', 'CANCEL_LISTING', 'BURN', 'APPROVE', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='transactionstatus'), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=True),
    sa.Column('value_wei', sa.String(length=78), nullable=True),
    sa.Column('gas_used', sa.Integer(), nullable=True),
    sa.Column('gas_price_wei', sa.String(length=78), nullable=True),
    sa.Column('nft_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_from_address'), ['from_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_hash'), ['tx_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_tx_type'), ['tx_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_tx_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_from_address'))

    op.drop_table('transactions')
    with op.batch_alter_table('mint_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mint_requests_status'))
        batch_op.drop_index(batch_op.f('ix_mint_requests_id'))

    op.drop_table('mint_requests')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_listing_id'))
        batch_op.drop_index(batch_op.f('ix_listings_id'))

    op.drop_table('listings')
    with op.batch_alter_table('nfts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfts_token_id'))
        batch_op.drop_index(batch_op.f('ix_nfts_mint_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_nfts_id'))
        batch_op.drop_index(batch_op.f('ix_nfts_contract_address'))

    op.drop_table('nfts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
